### ISSUE TITLE
Joystick pour téléphone (touch sensor)

### ISSUE THREAD

**Issue by sandros06** [sandros06/R-3D#10]
Implémenter un joystick pour téléphone. 
Dans la catégorie "touch sensor"

-Voir des inspirations sur internet 
-Implémenter avec un code minimal et simple (javascript et html/css) 
-Transmettre l'information du joystick par websocket (verifier les bornes) 
-Mouvance de l'objet 3D 

👍

**Comment by alix2018** [comment]
Projet virtual joystic js gihub (demo dispo) : https://github.com/yoannmoinet/nipplejs

**Comment by sandros06** [comment]
Script implémenté et fonctionnel, il manque plus que faire #12
