### ISSUE TITLE
Implémentation d'une application Android

### ISSUE THREAD

**Issue by sandros06** [sandros06/R-3D#13]
Objectif: Developper une application regroupant ce qu'on a fait précédemment, mais surtout sera utile pour l'analyse de la caméra 
- Discuter des technologies utilisé
(mais si nous utiliser du web, il sera facile d'ajouter tout ce qu'on a fait précédemment )
- Implémenter une caméra dans l'application 
- Ajouter des onglets pour les différentes méthodes etc...
 

(Ouvert à la discutions)

**Comment by thibautbuchert** [comment]
Je pense qu'il faudra le faire uniquement si on a des problèmes de performances. Je préfèrerais rester sur du web le plus longtemps possible : au moins, c'est portable.

**Comment by sandros06** [comment]
Mais comment veux-tu analyser la flux de la caméra avec du web ?

**Comment by thibautbuchert** [comment]
Vu les papiers que j'ai lus pour l'utilisation de la caméra, j'ai l'impression qu'on devra aller jusqu'au NDK sur android...
