### ISSUE TITLE
Utilisation de la caméra pour déterminer la position du téléphone

### ISSUE THREAD

**Issue by sandros06** [sandros06/R-3D#14]
Traitement des images directement par l’application (traitement simple)
But de produire des vecteurs de mouvance et rotation à envoyer à l'ordinateur. 

- Lire théorie et application (se documenter avant) 
- etc.. 

(à compléter)

**Comment by thibautbuchert** [comment]
Je suis désolé @sandros06 je n'ai pas compris ce que tu voulais dire.

**Comment by sandros06** [comment]
C'est exactement l'issue #26, il n'y a rien de difficile à comprendre :  tu as des images (vidéo), il faut les traiter pour ensuite envoyé des vecteurs de position (et de rotation)  

Après comment faire je ne sais pas (c'est pour sa que j'ai mis le tag help wanted car je ne connais ni la théorie et n'y comment procéder)

**Comment by thibautbuchert** [comment]
http://www.ifi.uzh.ch/dam/jcr:5759a719-55db-4930-8051-4cc534f812b1/VO_Part_I_Scaramuzza.pdf
http://rpg.ifi.uzh.ch/docs/VO_Part_II_Scaramuzza.pdf
http://rpg.ifi.uzh.ch/docs/Visual_Odometry_Tutorial.pdf

**Comment by thibautbuchert** [comment]
http://docs.opencv.org/3.2.0/da/de9/tutorial_py_epipolar_geometry.html

**Comment by thibautbuchert** [comment]
https://gist.github.com/thibautbuchert/75a7f8a5ec412e4745fae184a2f5af5a
