### ISSUE TITLE
Implémenter différente caméra de suivi

### ISSUE THREAD

**Issue by sandros06** [sandros06/R-3D#16]
Il faut réfléchir à différente implémentation de caméra de suivi d'objet 

- Camera statique on perçoit très bien le mouvement mais l'objet peut sortir du cadre
- Camera saccadé (une camera statique mais réactualise la position tout les x temps ou à certain condition)
- Camera suivi ( Caméra accroché à l'objet il faut implémenter un décor à carreau permettant de visualiser le mouvement) 

Voir d'autre solution

**Comment by sandros06** [comment]
A faire important car dans #28 la mouvance du cube a été implémenté et du coup la cube sort de l'écran, il faut absolument trouvé une solution pour la camera !

Pour les amateurs de Three.js à vos claviers 👍

**Comment by sandros06** [comment]
De plus si le menu d'option sont implémenté #17 on pourra facilement transiter entre les différentes camera

**Comment by AlexianMasson** [comment]
J'ai implémenté trois modes de suivis de caméra : 
- camera fixe
- caméra qui suit le cube à chaque frame
- caméra qui suit le cube avec une latence d'une seconde

J'ai aussi rajouté deux grilles pour mieux visualiser le déplacement.
