### ISSUE TITLE
Changer le design du site

### ISSUE THREAD

**Issue by sandros06** [sandros06/R-3D#17]
Peu important, mais permet de se distinguer avec ce qu'on avait déjà de base !
L'ergonomie peut être aussi utile et intéressant comme aspect à prendre en compte 

- Prendre une librairie de design : (bootstrap ou autre)
- Faire un design côté client simple (portable)
- Faire un design côté scène (PC - écran avec la scène 3D)

**Comment by sandros06** [comment]
Dans la page scène : il faudrait ajouter des panels sur le côté comme le panel d'option etc ...
Dans la page mobile : il faudrait faire une page auxiliaire pour choisir le mode qu'on veut (genre avec ou sans nipplejs)

**Comment by sandros06** [comment]
Ajout de notification 👍  https://eltimn.github.io/jquery-bs-alerts/

**Comment by alix2018** [comment]
Côté mobile c'est fait, il reste la scène : ajouter des panels sur le côté comme le panel d'option etc ...

**Comment by sandros06** [comment]
Besoin de menu ! continue dans #23
