### ISSUE TITLE
Ajouter des axes au cube

### ISSUE THREAD

**Issue by thibautbuchert** [sandros06/R-3D#22]
J'ai l'impression que les axes ne sont pas corrects ou que la caméra est mal placée. Ajouter les axes permettrait d'y voir plus clair.

**Comment by alix2018** [comment]
Ah oui c'est vrai on en avait parlé, tu as raison ce sera plus clair !

**Comment by sandros06** [comment]
Il faudrait ajouter des axes au point 0,0,0 qui ne bougent jamais (peut être décocher dans les futurs options)
De plus il faudrait aussi pouvoir décocher les axes du cube dans les options

**Comment by sandros06** [comment]
Les axes ont été ajouté, les aces sur 0,0,0 deviennent inutiles si la scène dispose d'un fond #30
