### ISSUE TITLE
Websocket à l'aide de la méthode du prof

### ISSUE THREAD

**Issue by sandros06** [sandros06/R-3D#6]
Envoyer des informations simples sur le téléphones à l'ordinateur
Envoyer les données des capteurs du téléphones à l'ordinateur 

Voir 2) pour la data

**Comment by sandros06** [comment]
Re-utilisation de code
Verifier le code

**Comment by AlexianMasson** [comment]
Je propose que l'on "formalise" le protocole de communication avec une fichier json pour envoyer les données des capteurs à l’ordinateur à travers la websocket. Ça va simplifier la récupération des données et le debugage.

Exemple : 
{
"rotation" : 0.5454,
"translation" : 0.6655
}

**Comment by thibautbuchert** [comment]
Je suis pas sûr que le JSON soit nécessaire, c'est pas plus simple de faire un protocole binaire ? Je pense qu'il faudrait séparer rotaiton et translation, parce l'envoi des coordonnées de rotation et de translation peut ne pas se faire en même temps.

**Comment by thibautbuchert** [comment]
(en vrai le JSON en websockets ça me fait penser à scoledge :hankey:)

**Comment by sandros06** [comment]
On a adopté le websocket avec la librairie du prof
