### ISSUE TITLE
Changer le rectangle en cube

### ISSUE THREAD

**Issue by alix2018** [sandros06/R-3D#7]
- Crée un cube 3D : dans le fichier scene.html, modifier les lignes qui servent à créer le rectangle rouge (ligne 70, voir code suivant)
`const planeMaterial = new THREE.MeshLambertMaterial({ color: 0xCC0000, side: THREE.DoubleSide });
        const plane = new THREE.Mesh(new THREE.PlaneGeometry(PLANE_W, PLANE_H), planeMaterial);`

**Comment by sandros06** [comment]
C'est bon !
